name: Test

on:
  push:
  pull_request:
  schedule:
    - cron: "0 5 * * 6"

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version:
          - 3.6
          - 3.7
          - 3.8
          - 3.9
          - '3.10'
          - pypy3

    runs-on: ubuntu-latest

    steps:
      - name: Setup Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install Poetry
        uses: jayclassless/setup-poetry-action@v1

      - name: Checkout Code
        uses: actions/checkout@v2

      - name: Install
        run: |
          make setup
          make env

      - name: Test
        run: |
          make test
